### ISSUE TITLE
Suggestion: check item -> entityType map in matchFishEntity

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Pyxrs/Live-Fishing#1]
You could create `public static final Map<Item, EntityType<?>> FISHABLE_ITEM_MAP = new HashMap<>();` in a public class, and then change your `matchFishEntity` method to 
```java
private static Optional<FishEntity> matchFishEntity(World world, Item item) {
    return Optional.ofNullable(FISHABLE_ITEM_MAP.get(item));
}
```

Then you could put all the vanilla fish items with their entity types in the map, and other mods could do the same with their fish-able items. 

You may want to make the map private and access it though setters and getters and ensure no mapping is ever removed, but those're details.

**Comment by Pyxrs** [comment]
I considered using a HashMap but I couldn't get the implementation right. Thanks! I will try again

**Comment by supersaiyansubtlety** [comment]
Mod is now data driven, so other mods can add compat via their data directory. 
That makes this issue obsolete.
