### ISSUE TITLE
Fish from other mods come out as the item.

### ISSUE THREAD

**Issue by Ibex80** [Pyxrs/Live-Fishing#2]
You should add a json file that people can add their fish to, so that they come out as the mod.
You would have to specify the modid, the fish entity, the fish item, and that chance of it being caught.

**Comment by Pyxrs** [comment]
The way the mixin works is it gets the item that would be spawned, and if it matches a predefined entity, then it spawns that entity to interfere as little as possible with normal fishing mechanics. That is a good idea, and I will consider implementing it (I'm just terrible at data-driven stuff lol)

**Comment by Jab125** [comment]
Just make an api to do it :) make the api add the entity to a￼n array list or something
